services:
  central_junior_web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/central_junior
    depends_on:
      - central_junior_db
      - central_junior_redis

  central_junior_db:
    image: postgres:18
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: central_junior

  central_junior_redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
